BEGIN{
    print "NAME, ID, STATE, RESTART POLICY, CREATED, IMAGE, IMAGE ID, ENTRYPOINT, COMMAND, STORAGE DRIVER, CONTAINER LAYER, PORTS"
}
BEGIN { RS = "" ; FS = "(\n|: )"; OFS="," }

{
    print $1, $3, $5, $7, $9, $11, $13, $15, $17, $19, $21, $23
}
